# Generated by Django 5.2.10 on 2026-05-06 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankTariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank', models.CharField(choices=[('tbank', 'Т-Банк'), ('sberbank', 'Сбербанк'), ('alfa', 'Альфа-Банк'), ('other', 'Другой банк')], default='tbank', max_length=20, verbose_name='Банк')),
                ('name', models.CharField(max_length=100, verbose_name='Название тарифа')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('is_default', models.BooleanField(default=False, help_text='Только один тариф может быть тарифом по умолчанию', verbose_name='По умолчанию')),
                ('maintenance_fee', models.DecimalField(decimal_places=2, default=490, max_digits=10, verbose_name='Обслуживание счёта, ₽/мес')),
                ('maintenance_free_condition', models.TextField(blank=True, default='Нет операций ИЛИ покупки по бизнес-карте от 150 000 ₽/мес', verbose_name='Условие бесплатного обслуживания')),
                ('outgoing_same_bank_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Перевод поставщику в том же банке, ₽')),
                ('outgoing_other_bank_fee', models.DecimalField(decimal_places=2, default=49, max_digits=10, verbose_name='Перевод поставщику в другой банк, ₽')),
                ('withdrawal_config', models.JSONField(default=dict, help_text='Прогрессивная шкала комиссий за вывод. up_to=null означает «без верхней границы».', verbose_name='Настройки вывода на карту (JSON)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Банковский тариф',
                'verbose_name_plural': 'Банковские тарифы',
                'ordering': ['bank', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TaxSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=2026, unique=True, verbose_name='Год')),
                ('fixed_insurance_annual', models.DecimalField(decimal_places=2, default=49500, help_text='Обязательные взносы на ОПС + ОМС без сотрудников. 2026 г. — 49 500 ₽.', max_digits=12, verbose_name='Фиксированные взносы ИП за год, ₽')),
                ('additional_insurance_threshold', models.DecimalField(decimal_places=2, default=300000, max_digits=12, verbose_name='Порог дохода для 1%, ₽/год')),
                ('additional_insurance_rate', models.DecimalField(decimal_places=2, default=1, max_digits=5, verbose_name='Ставка дополнительного взноса, %')),
            ],
            options={
                'verbose_name': 'Настройки налогов',
                'verbose_name_plural': 'Настройки налогов',
                'ordering': ['-year'],
            },
        ),
    ]
