# Generated by Django 5.2.10 on 2026-05-06 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_initial_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название компании или площадки (Wildberries, ООО Ромашка и т.д.)', max_length=200, verbose_name='Поставщик')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Цена за единицу, ₽')),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Стоимость доставки, ₽')),
                ('delivery_days', models.PositiveIntegerField(default=0, verbose_name='Срок поставки, дней')),
                ('document_url', models.URLField(blank=True, help_text='URL файла КП, страницы товара или облачного документа', verbose_name='Ссылка на КП / товар')),
                ('comment', models.TextField(blank=True, help_text='Особые условия, минимальная партия, качество и т.д.', verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')),
            ],
            options={
                'verbose_name': 'КП поставщика',
                'verbose_name_plural': 'КП поставщиков',
                'ordering': ['unit_price', 'shipping_cost'],
            },
        ),
    ]
