# Generated by Django 5.2.10 on 2026-05-07 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0003_add_vendor_offer'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_monthly_revenue', models.DecimalField(decimal_places=2, default=0, help_text='Типичный ежемесячный оборот ИП. Используется для пропорционального распределения фиксированных взносов и обслуживания счёта по сделкам.', max_digits=14, verbose_name='Ожидаемая выручка в месяц, ₽')),
            ],
            options={
                'verbose_name': 'Настройки приложения',
                'verbose_name_plural': 'Настройки приложения',
            },
        ),
    ]
