# Generated by Django 5.2.10 on 2026-05-07 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0004_app_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование товара')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('unit', models.CharField(default='шт.', help_text='шт., кг, м, л, уп. и т.д.', max_length=20, verbose_name='Единица измерения')),
                ('description', models.TextField(blank=True, verbose_name='Описание / требования')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Потребность',
                'verbose_name_plural': 'Потребности',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupplierOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=200, verbose_name='Поставщик')),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Цена за единицу, ₽')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=14, verbose_name='Итоговая сумма, ₽')),
                ('delivery_days', models.PositiveIntegerField(blank=True, null=True, verbose_name='Срок доставки, дней')),
                ('link', models.URLField(blank=True, verbose_name='Ссылка на товар / КП')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='calculator.requirement', verbose_name='Потребность')),
            ],
            options={
                'verbose_name': 'КП поставщика',
                'verbose_name_plural': 'КП поставщиков',
                'ordering': ['total_price'],
            },
        ),
    ]
