# Generated by Django 5.2.10 on 2026-05-07 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0005_requirement_supplieroffer'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='short_name',
            field=models.CharField(blank=True, help_text='Краткое название для таблиц и списков (до 60 символов)', max_length=60, verbose_name='Сокращённое наименование'),
        ),
    ]
