# Generated by Django 5.2.10 on 2026-05-07 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0006_add_short_name_to_requirement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название поставки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Поставка',
                'verbose_name_plural': 'Поставки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='calculator.delivery', verbose_name='Поставка')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_items', to='calculator.requirement', verbose_name='Потребность')),
                ('selected_offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_items', to='calculator.supplieroffer', verbose_name='Выбранное КП')),
            ],
            options={
                'verbose_name': 'Позиция поставки',
                'verbose_name_plural': 'Позиции поставки',
                'ordering': ['requirement__name'],
                'unique_together': {('delivery', 'requirement')},
            },
        ),
    ]
