# Generated by Django 5.2.10 on 2026-05-08 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0007_add_delivery_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Название сделки')),
                ('client_name', models.CharField(blank=True, max_length=200, verbose_name='Заказчик / клиент')),
                ('invoice_number', models.CharField(blank=True, max_length=100, verbose_name='Номер счёта / договора')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('purchased', 'Закуплено'), ('delivered', 'Поставлено'), ('paid', 'Оплачено клиентом'), ('cancelled', 'Отменена')], default='draft', max_length=20, verbose_name='Статус')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='Дата закупки')),
                ('delivery_date', models.DateField(blank=True, null=True, verbose_name='Дата поставки')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='Дата оплаты клиентом')),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Выручка (цена для клиента), ₽')),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Себестоимость, ₽')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Налог, ₽')),
                ('bank_commission', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Комиссия банка, ₽')),
                ('insurance_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Страховые взносы, ₽')),
                ('other_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Прочие расходы, ₽')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('delivery', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deal', to='calculator.delivery', verbose_name='Поставка')),
            ],
            options={
                'verbose_name': 'Сделка',
                'verbose_name_plural': 'Сделки',
                'ordering': ['-created_at'],
            },
        ),
    ]
