# Generated by Django 5.2.10 on 2026-05-08 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0008_add_deal_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='Автоматически архивируется при переводе сделки в статус «Оплачено»', verbose_name='В архиве'),
        ),
    ]
