# Generated by Django 5.2.10 on 2026-05-08 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0009_add_requirement_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='gross_tax',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Налог до вычета страховых взносов', max_digits=14, verbose_name='Начисленный налог (до вычета), ₽'),
        ),
        migrations.AddField(
            model_name='deal',
            name='tax_system',
            field=models.CharField(blank=True, max_length=20, verbose_name='Система налогообложения'),
        ),
    ]
