# Generated by Django 5.2.10 on 2026-05-08 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0011_delivery_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplieroffer',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='offers/', verbose_name='Файл КП'),
        ),
    ]
